name: Go fuzz test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test-suite:
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v2

      - name: Setup Golang
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v1
        with:
          go-version: '1.19'

      - name: Fuzz test
        run: |
          GO111MODULE=on go mod tidy
          GO111MODULE=on go mod vendor
          ./tools/fuzz-all.sh 30
